export enum RnMqttEventParams {
  SERVER_URI = 'SERVER_URI',
  CLIENT_REF = 'CLIENT_REF',
  ERR_MESSAGE = 'ERR_MESSAGE',
  ERR_CODE = 'ERR_CODE',
  STACKTRACE = 'STACKTRACE',
  TOPIC = 'TOPIC',
  PAYLOAD = 'PAYLOAD',
  QOS = 'QOS',
  RETAIN = 'RETAIN',
}
