import Foundation

enum QuitoEvent: String, CaseIterable {
  case EXCEPTION = "EXCEPTION"
  case RECONNECT = "RECONNECT"
  case CONNECTING = "CONNECTING"
  case CONNECTED = "CONNECTED"
  case CLOSED = "CLOSED"
  case DISCONNECTED = "DISCONNECTED"
  case SUBSCRIBED = "SUBSCRIBED"
  case UNSUBSCRIBED = "UNSUBSCRIBED"
  case CONNECTION_LOST = "CONNECTION_LOST"
  case MESSAGE_RECEIVED = "MESSAGE_RECEIVED"
  case MESSAGE_PUBLISHED = "MESSAGE_PUBLISHED"
  case DELIVERY_COMPLETE = "DELIVERY_COMPLETE"
  case CONNECTION_COMPLETE = "CONNECTION_COMPLETE"
  case CLIENT_REF_UNKNOWN = "CLIENT_REF_UNKNOWN"
}