require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'QuitoExample' do
  config = use_native_modules!
  use_frameworks! :linkage => :static

  use_react_native!(:path => config["reactNativePath"])

  pod 'quito', :path => '../..'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!({ 'Flipper' => '0.80.0' })
  #post_install do |installer|
  #  flipper_post_install(installer)
  #end
  post_install do |installer|
    installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
         config.build_settings.delete "IPHONEOS_DEPLOYMENT_TARGET"
     end
     case target.name
         when 'RCT-Folly'
           target.build_configurations.each do |config|
             config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
           end
         end
    end
   end
end
