package com.rnmqtt.models.rnevents

enum class RnMqttEvent {
  EXCEPTION,
  RECONNECT,
  CONNECTING,
  CONNECTED,
  CLOSED,
  DISCONNECTED,
  SUBSCRIBED,
  UNSUBSCRIBED,
  CONNECTION_LOST,
  MESSAGE_RECEIVED,
  MESSAGE_PUBLISHED,
  DELIVERY_COMPLETE,
  CONNECTION_COMPLETE,
  CLIENT_REF_UNKNOWN
}
